-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mod = "SUPER"

--GENERAL#

--Monitor settings
hl.monitor({
    output = "HDMI-A-2",
    mode = "2560x1440@280",
    position = "0x0",
    scale = 1,
    vrr = 0,
})

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@144",
    position = "2560x-900",
    scale = 1,
    transform = 1,
    vrr = 0,
})

--monitor=DP-1,disable

-- WS on HDMI-A-2
hl.workspace_rule({
    workspace = "1",
    monitor = "HDMI-A-2",
    persistent = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "HDMI-A-2",
    persistent = true,
})

-- WS on DP-1
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "4",
    monitor = "DP-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "5",
    monitor = "DP-1",
    persistent = true,
})

hl.window_rule({
    name = "windowrule-1",
    match = {
        title = "^RuneLite.*",
    },
    float = true,
})

hl.window_rule({
    name = "windowrule-2",
    match = {
        class = "net-runelite-client-RuneLite",
        title = "win.*",
    },
    no_focus = true,
})

hl.window_rule({
    name = "windowrule-3",
    match = {
        class = ".*",
    },
    immediate = true,
})

--windowrulev2 = maxsize 1803 1153,title:^(RuneLite)$
--windowrulev2 = maxsize 1803 1153,title:^(RuneLite)$

hl.layer_rule({
    name = "layerrule-1",
    match = {
        namespace = "waybar",
    },
    blur = true,
    ignore_alpha = 0,
    blur_popups = true,
})

hl.layer_rule({
    name = "layerrule-2",
    match = {
        namespace = "walker",
    },
    ignore_alpha = 0,
    blur = true,
})

hl.layer_rule({
    name = "layerrule-3",
    match = {
        namespace = "notifications",
    },
    ignore_alpha = 0,
    blur = true,
})

hl.bind(mod .. " + SHIFT + S", hl.dsp.exec_cmd("/nix/store/bymxsrjyrphiz7ds61mw9fcg34h57x02-imsh-shot/bin/imsh-shot area -Cufa@~/.config/keys/scrnis -s1"))
hl.bind(mod .. " + SHIFT + F", hl.dsp.exec_cmd("/nix/store/bymxsrjyrphiz7ds61mw9fcg34h57x02-imsh-shot/bin/imsh-shot screen -Cua@~/.config/keys/scrnis"))
hl.bind(mod .. " + SHIFT + R", hl.dsp.exec_cmd("/nix/store/bymxsrjyrphiz7ds61mw9fcg34h57x02-imsh-shot/bin/imsh-cast -Cua@~/.config/keys/scrnis"))
hl.bind(mod .. " + Return", hl.dsp.exec_cmd("walker"))
hl.bind(mod .. " + T", hl.dsp.exec_cmd("kitty"))
hl.bind(mod .. " + W", hl.dsp.exec_cmd("firefox"))
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + G", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "m+1" }))
hl.bind(mod .. " + mouse_up", hl.dsp.focus({ workspace = "m-1" }))
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize())
hl.bind(mod .. " + Delete", hl.dsp.exit())

hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("XCURSOR_THEME", "BreezeX-Black")
hl.env("XCURSOR_SIZE", "28")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.config({
    general = {
        border_size = 2,
        gaps_in = 5,
        gaps_out = 17,
        layout = "dwindle",
        col = {
            active_border = "rgb(aaffff)",
            inactive_border = "rgba(00000000)",
        },
        allow_tearing = true,
    },
    decoration = {
        rounding = 10,
        blur = {
            enabled = true,
            size = 9,
            passes = 3,
            new_optimizations = true,
        },
        shadow = {
            enabled = false,
            render_power = 3,
            range = 4,
            color = "rgba(1a1a1aee)",
        },
    },
    input = {
        kb_layout = "no",
        follow_mouse = 1,
        sensitivity = 0,
        accel_profile = "flat",
    },
    --MISC#
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
    },
    ecosystem = {
        no_donation_nag = true,
    },
    --BINDS#
    binds = {
        scroll_event_delay = 10,
    },
    --EXEC#
    --ENVIROMENT#
    --CURSOR#
    cursor = {
        no_hardware_cursors = true,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("env LC_TIME=en_GB.UTF-8 waybar")
    hl.exec_cmd("dunst")
    hl.exec_cmd("walker --gapplication-service")
    hl.exec_cmd("elephant")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("xembedsniproxy")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
   -- hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme prefer-dark")
   -- hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme Adwaita-dark")
end)

